### ISSUE TITLE
would you like to incorporate the work with jasync-sql?

### ISSUE THREAD

**Issue by oshai** [mirromutth/r2dbc-mysql#1]
Recently, there has been a request for jasync-sql to support r2dbc: https://github.com/jasync-sql/jasync-sql/issues/98 . jasync-sql supports MySQL already and we're building a bridge to r2dbc.

Would you like to merge the efforts?

**Comment by mp911de** [comment]
This is actually a pretty decent proposal. Having fully reactive components as core engine is of huge value because the core architecture dictates how capable an entire driver can be.

The core functionality can be either exposed through a reactive streaming API (emitting items one by one, flow control, backpressure) or a less capable API (e.g. working on `CompletableFuture<List<Row>>` or even `CompletableFuture<ResultSet>` level).

**Comment by mirromutth** [comment]
Just like @mp911de said, this is actually a pretty decent proposal. I'm watching `jasync-sql` now. I will try to get familiar with your project before I fork from and submit PR to your repository. And I know [Mauricio Linhares driver](https://github.com/mauricio/postgresql-async) already has NOT been maintenanced ([postgresql-async#250](https://github.com/mauricio/postgresql-async/issues/250)), which used by Vert.x frameworks (I haven't paid attention to Vert.x for a long time because of my work, it looks like the Vert.x framework is now more recommended to use `jasync-sql`).

One of my ideas is to provide this clean room implementation (`mirromutth/r2dbc-mysql`) without any `mysql-connector-j` code and structure, because  `mysql-connector-j` licensed under GPLv2 license, and the R2DBC projects uses Apache 2.0 license, they are conflicting licenses.

**Comment by oshai** [comment]
Great! I started a very initial implementation on this PR: https://github.com/jasync-sql/jasync-sql/pull/99 . You're welcome to use it as a reference and continue from there.

**Comment by mirromutth** [comment]
I will continue to follow the r2dbc support on `jasync-sql`, this issue will be closed, see [jasync-sql](https://github.com/jasync-sql/jasync-sql)
