### ISSUE TITLE
Custom type encoding (UUID)

### ISSUE THREAD

**Issue by adrilo** [mirromutth/r2dbc-mysql#101]
Hi,

I'm trying to insert a UUID in a DB but the `save` call fails saying that there are no encoders supporting this type. Indeed `DefaultCodecs` does not have a `UUIDCodec`. I was not able to find a way to add a custom Codec though. Did I miss something? How would you recommend I can fix my problem?

For context, my DAO looks like this:
```
class Person {
  @Id
  Long id;
  UUID userUuid;
  String name;
}
```

**Comment by adrilo** [comment]
I managed to achieve what I want by registering custom Converters:
```
public class MySQLConfiguration extends AbstractR2dbcConfiguration {
    @Override
    protected List<Object> getCustomConverters() {
        return List.of(new UUIDToByteArrayConverter(), new ByteArrayToUUIDConverter());
    }
    ...
}

@WritingConverter
public class UUIDToByteArrayConverter implements Converter<UUID, byte[]> {
    @Override
    public byte[] convert(UUID source) {
        ByteBuffer bb = ByteBuffer.wrap(new byte[16]);
        bb.putLong(source.getMostSignificantBits());
        bb.putLong(source.getLeastSignificantBits());
        return bb.array();
    }
}

@ReadingConverter
public class ByteArrayToUUIDConverter implements Converter<byte[], UUID> {
    @Override
    public UUID convert(byte[] source) {
        return UUID.nameUUIDFromBytes(source);
    }
}
```

Still, given the large usage of UUIDs, it may be worth adding a codec for this type as part of the default set.

**Comment by adrilo** [comment]
Well it turns out saving to the DB works with the method described above but parameter binding still does not work. I forgot to mention that the UUID is stored as a `VARBINARY(16)`.

Basically, if I have a repository like this:
```
@Repository
public interface PersonRepository extends R2dbcRepository<Person, String> {

    @Query("SELECT * FROM person WHERE uuid = :uuid")
    Flux<Person> findByUuid(UUID uuid); // <= does not work

    @Query("SELECT * FROM place WHERE uuid = :uuid")
    Flux<Place> findByByteArrayUuid(byte[] uuid); <= works
}
```

Adding a way to provide custom codec or adding a UUIDCodec in the default codec set would help in that case.

Am I missing something?

**Comment by mirromutth** [comment]
Hi there, thanks for your suggestion.

The principle of R2DBC MySQL features' provision is: "Compliant with R2DBC Specification, providing the same or compatible JDBC features."

See https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spec/src/main/asciidoc/data-types.adoc , that means if MySQL does not support UUID, driver will be not provide UUID data type. (In fact, MySQL does not support UUID)

See also the behavior of `mysql-connector-j`, it serialize UUID with stringify, that means it will be looks like `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` instead of binaries.

And, see also the deserialization of UUID in `mysql-connector-j`. If we are calling `resultSet.getObject(index, UUID.class)`, we will get the conversation exception: `java.sql.SQLException: Conversion not supported for type java.util.UUID`.

One more thing, the `Converter` is a feature of `spring-data-r2dbc`, so it is an application-level framework feature instead of a driver-level feature.

So, there are three questions:

- Do we should support `UUID` serialization/deserialization?
- If we must support it, should we support it in driver codecs, or in `spring-data-r2dbc` convertors?
- If we must support it, should we use stringify-UUID or binarized-UUID?

**Comment by mp911de** [comment]
I don't see there's a need to provide a UUID codec for MySQL R2DBC. Similar to enums, there are simply too many options for how the value could be represented. 

Spring Data allows registration of custom converters to tweak how non-native values should be represented in the database. 

Right now, I have no idea whether it would make sense to provide a configuration mechanism for `Codecs` so users can register their own codecs. For Postgres, it made sense as Postgres has a pluggable and extensible type system.

**Comment by adrilo** [comment]
Is there a way to register a converter to do `findByXXXX(T myNotStandardObject)` (e.g. `findByUUID(UUID uuid)`? I only found a way to save/retrieve objects containing non standard attributes but was not able to solve this problem.

If there's a way to do that, then I agree it's better to leave that to Spring Data. If not, I'm not sure which layer would be the best to implement such a change. My knowledge about these libs are not what I wish it would be at, so I'm letting you guys take the decision.

**Comment by mp911de** [comment]
In short, Spring Data R2DBC is the right place for these conversions. I filed spring-projects/spring-data-r2dbc#305 as the converter support isn't consistent at the moment.

**Comment by adrilo** [comment]
Great! Thanks for following-up @mp911de

**Comment by Tuegor** [comment]
> Hi there, thanks for your suggestion.
> 
> The principle of R2DBC MySQL features' provision is: "Compliant with R2DBC Specification, providing the same or compatible JDBC features."
> 
> See https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spec/src/main/asciidoc/data-types.adoc , that means if MySQL does not support UUID, driver will be not provide UUID data type. (In fact, MySQL does not support UUID)

Good at evasions, huh? It that's so, why does Spring Data JPA with a non-reactive driver support it no sweat? I'll tell you why - because your statement is a lie. MySQL does support UUID, although it doesn't have a separate data type for it like Postgres. That's why it has the UUID() function, whose return value can be stored in a CHAR column. And if you apply UUID_TO_BIN() function to this value, you can store it compressed in a BINARY column.
So say it straight - you are plain lazy to implement it, although it's needed and two years have passed since this report.

**Comment by dehidehidehi** [comment]
The previous solution would result in incorrect UUID conversion back and forth. 

I have made the suggested improvement to the converter implementation. Here is the updated code:

```java
@WritingConverter
public static class UUIDWriteConverter implements Converter<UUID, byte[]> {
    @Override
    public byte[] convert(final UUID source) {
        final var bb = ByteBuffer.wrap(new byte[16]);
        bb.putLong(source.getMostSignificantBits());
        bb.putLong(source.getLeastSignificantBits());
        return bb.array();
    }
}

@ReadingConverter
public static class UUIDReadConverter implements Converter<byte[], UUID> {
    @Override
    public UUID convert(final byte[] source) {
        final var bb = ByteBuffer.wrap(source);
        final var firstLong = bb.getLong();
        final var secondLong = bb.getLong();
        return new UUID(firstLong, secondLong);
    }
}
```

This fix ensures that the UUID is correctly converted back and forth between bytes.
