### ISSUE TITLE
serverZoneId option not working

### ISSUE THREAD

**Issue by sumitsum** [mirromutth/r2dbc-mysql#163]
I have created my connection like this: 
```
MySqlConnectionConfiguration configuration = MySqlConnectionConfiguration.builder()
                    .host("localhost")
                    .user("test")
                    .port(3306)
                    .password("mydbpassword")
                    .database("mytestdb")
                    .serverZoneId(ZoneId.of("Australia/Darwin"))
                    .build();
            ConnectionFactory connectionFactory = MySqlConnectionFactory.from(configuration);

            return (Mono<Connection>) Mono.from(connectionFactory.create())
                    .onErrorResume(exception -> {
                        log.debug("Error when creating datasource.", exception);
                        return Mono.error(Exceptions.propagate(exception));
                    })
                    .subscribeOn(scheduler);
```

When fetching timestamp type from mysql server, the value fetched by the driver had not changed the timestamp values as per the zone. 

My test table: 
mysql> select * from test_date_time_types;
+------------+---------------------+---------------------+----------+--------+
| c_date     | c_datetime          | c_timestamp         | c_time   | c_year |
+------------+---------------------+---------------------+----------+--------+
| 2020-12-01 | 2020-12-01 20:20:20 | 2020-12-01 20:20:20 | 20:20:20 |   2020 |
+------------+---------------------+---------------------+----------+--------+

**Comment by mirromutth** [comment]
Hi there,

Sorry for the late reply.

The `LocalDateTime` will favor to use the original value you stored, and `ZonedDateTime`/`OffsetDateTime` will use server timezone and original value. 

It should be noticed that these three **datetime**s (`LocalDateTime`/`ZonedDateTime`/`OffsetDateTime`) are not strictly **timestamp**. They consist of year, month, day, hour, minute, second, nanosecond, timezone id (`ZonedDateTime` only), timezone offset (`OffsetDateTime` only).

So, if you want to get the **timestamp**, should call `Row.get(index, Instant.class)` instead. If you want to get the **datetime** after the timezone conversion, should call `Row.get(index, ZonedDateTime.class).withZoneSameInstant(ZoneId.systemDefault())`.

In my limited experience with date and time system, the **timestamp** does not defined by timezone. As far as I know, the **datetime** (year-month-day hour:minute:second.nanosecond) is formatted by **timestamp** with timezone offset. This means that the **timestamp** does not change due to changes in timezone. In other words, if we do not consider clock skew and clock back, all **timestamp**s should be consistent on all systems (hmmm, the real world is always unsatisfactory).

If the problem or more questions persists, please continue reply.

Best Regards,

**Comment by Paramood** [comment]
Hi,

If reading `timestamp` field as `Instant`, it gets wrong value. Tried setting `serverZoneId` to UTC. This doesn't help.

E.g. DB stores `2021-06-30 13:46:50` but when reading as `Instant`, the obtained value is `2021-06-30T10:46:50Z`.

But write to DB works OK even without this config. `LocalDateTime` works normally for both write and read.
