### ISSUE TITLE
Should support truly prepared statement?

### ISSUE THREAD

**Issue by mirromutth** [mirromutth/r2dbc-mysql#4]
@mp911de I have a problem for prepared statement in MySQL.

I noticed that even `mysql-connector-j` is actually implemented using a text query statement when implementing a prepare statement. In other words, it will replace the illegal characters and directly spliced ​​into the SQL statement.

If need to implement a truly prepared statement, will encounter the following challenges:

- MySQL's official library, at least `mysql-connector-j` can not give any help, can only read the API documentation with less description
- `mysql-connector-j` is doing very well in all production environments. (OK, let's forget the unpleasant things...)
- Sequence id makes concurrent requests difficult, because truly prepared statement has multi frontend messages, and each message should wait last message response before it send (because the sequence id always needs to be increased whether message is inbound or outbound, until the OK message or error message is returned).
   - If we always use simple text query, it only has single request message which sequence id is 0 (ignore big data), and multi text result packets which sequence id from 1 to X (last packet must be OK or error), so we can make sure every request packet's sequence id is increment from 0. Then we could send multi-request without any wait.
   - The exit message is obviously a very important message that needs to be sent immediately. If need to wait for the last response, it may lead to some unpredictable problems.

Below is the code snippet and Socket fragment I intercepted:

```Java
try (Connection connection = dataSource.getConnection()) {
    try (PreparedStatement statement = connection.prepareStatement("SELECT COUNT(0) FROM work_base WHERE `name` = ?")) {
        statement.setString(1, "' OR 1 = 1 OR '' = '");
        statement.executeQuery();

        statement.setString(1, "' OR 0 = 0 OR '' = '");
        statement.executeQuery();
    }
}
```

Socket packets:

```
0000   49 00 00 00 03 53 45 4c 45 43 54 20 43 4f 55 4e   I....SELECT COUN
0010   54 28 30 29 20 46 52 4f 4d 20 77 6f 72 6b 5f 62   T(0) FROM work_b
0020   61 73 65 20 57 48 45 52 45 20 60 6e 61 6d 65 60   ase WHERE `name`
0030   20 3d 20 27 5c 27 20 4f 52 20 31 20 3d 20 31 20    = '\' OR 1 = 1 
0040   4f 52 20 5c 27 5c 27 20 3d 20 5c 27 27            OR \'\' = \''
...
0000   49 00 00 00 03 53 45 4c 45 43 54 20 43 4f 55 4e   I....SELECT COUN
0010   54 28 30 29 20 46 52 4f 4d 20 77 6f 72 6b 5f 62   T(0) FROM work_b
0020   61 73 65 20 57 48 45 52 45 20 60 6e 61 6d 65 60   ase WHERE `name`
0030   20 3d 20 27 5c 27 20 4f 52 20 30 20 3d 20 30 20    = '\' OR 0 = 0 
0040   4f 52 20 5c 27 5c 27 20 3d 20 5c 27 27            OR \'\' = \''
```

**Comment by mirromutth** [comment]
I guess this is why jasync can't send a request when exchanging, because it use truly prepared statement.

**Comment by mp911de** [comment]
Appreciate to hear that you want to tackle such a complex issue. I'm not entirely sure I understood the message flow. Let me tell you what we have for SQL Server:

In SQL Server we can either send a statement directly or use cursors. A cursored message flow using parametrized statements requires prepared statement call (it either prepares or reuses a prepared statement), then we fetch data from the cursor and close the cursor after consuming all data.

The message flow is synchronous: We need to issue a command and await the response before we can continue with the next (read from cursor) message. Same for read from cursor response. We need to await that one before closing the cursor.

Take a look at [`RpcQueryMessageFlow.exchange()`](https://github.com/r2dbc/r2dbc-mssql/blob/master/src/main/java/io/r2dbc/mssql/RpcQueryMessageFlow.java#L208-L275) and its `handleMessage(…)` method that considers the message flow. Probably that's something you're looking for.

In R2DBC, a single connection can be used only by a single conversation. We cannot (should not) expect to issue multiple commands on a single connection because that's not the way databases work.

In SQL Server we also have the concept of a sequence Id (it's called PacketId, but sounds basically the same to me). I implemented it as [`PacketIdProvider`](https://github.com/r2dbc/r2dbc-mssql/blob/master/src/main/java/io/r2dbc/mssql/message/header/PacketIdProvider.java) that is bound to a connection. This makes it simple to atomically increment a counter. With the assumption that a connection is used synchronously by a single subscriber, we exclude the concurrency aspect.

Does this help?

**Comment by mirromutth** [comment]
`r2dbc-mssql`'s packet id implementation is very useful for me, thanks very much.

The answer is yes, this driver should support truly prepared statement.
